name: First Action Workflow
on: push

jobs:
    build:
      name: Build First Action
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: ./action-a
          with:
            MY_NAME: "Alon"